import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'

export default async function AdminUsersPage() {
  const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
      if (!user) redirect('/login')

        const { data: profile } = await supabase.from('profiles').select('role').eq('id', user.id).single()
          if (profile?.role !== 'admin') redirect('/dashboard/admin')

            const { data: users } = await supabase
                .from('profiles')
                    .select('*, institutes(name)')
                        .order('created_at', { ascending: false })

                          const userList = users ?? []

                            const roleColors: Record<string, string> = {
                                admin: 'bg-purple-100 text-purple-700',
                                    profesor: 'bg-blue-100 text-blue-700',
                                        alumno: 'bg-green-100 text-green-700',
                                          }

                                            return (
                                                <div className="p-8 max-w-6xl mx-auto">
                                                      <h1 className="text-2xl font-bold text-[#050F1F] mb-2">Usuarios</h1>
                                                            <p className="text-[#050F1F]/50 mb-8">{userList.length} usuarios registrados en la plataforma.</p>
                                                                  <div className="bg-white rounded-2xl border border-black/5 shadow-sm overflow-hidden">
                                                                          <table className="w-full text-sm">
                                                                                    <thead className="bg-[#F0F9FF] border-b border-black/5">
                                                                                                <tr>
                                                                                                              <th className="text-left px-5 py-3 text-[#050F1F]/50 font-medium">Usuario</th>
                                                                                                                            <th className="text-left px-5 py-3 text-[#050F1F]/50 font-medium">Rol</th>
                                                                                                                                          <th className="text-left px-5 py-3 text-[#050F1F]/50 font-medium">Instituto</th>
                                                                                                                                                        <th className="text-left px-5 py-3 text-[#050F1F]/50 font-medium">Registro</th>
                                                                                                                                                                    </tr>
                                                                                                                                                                              </thead>
                                                                                                                                                                                        <tbody className="divide-y divide-black/5">
                                                                                                                                                                                                    {userList.map((u: any) => (
                                                                                                                                                                                                                  <tr key={u.id} className="hover:bg-[#F0F9FF]/50 transition-colors">
                                                                                                                                                                                                                                  <td className="px-5 py-3.5">
                                                                                                                                                                                                                                                    <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                        <div className="w-8 h-8 rounded-full bg-gradient-to-br from-[#1A56DB] to-[#38BDF8] flex items-center justify-center text-white text-xs font-bold flex-shrink-0">
                                                                                                                                                                                                                                                                                              {(u.full_name || u.email || '?').charAt(0).toUpperCase()}
                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                            <p className="font-medium text-[#050F1F]">{u.full_name || 'Sin nombre'}</p>
                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-xs text-[#050F1F]/40">{u.email}</p>
                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <td className="px-5 py-3.5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className={`px-2.5 py-1 rounded-full text-xs font-medium ${roleColors[u.role] ?? 'bg-gray-100 text-gray-600'}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {u.role}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <td className="px-5 py-3.5 text-[#050F1F]/60">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {u.institutes?.name ?? <span className="text-[#050F1F]/30">—</span>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td className="px-5 py-3.5 text-[#050F1F]/40">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {new Date(u.created_at).toLocaleDateString('es-AR', { dateStyle: 'short' })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }